// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs-MTPzF0uGsWGLEGZXz_7d913rUjrOZc',
    appId: '1:422878767311:web:6db828cb388d6ebff1efba',
    messagingSenderId: '422878767311',
    projectId: 'inventariobyl',
    authDomain: 'inventariobyl.firebaseapp.com',
    storageBucket: 'inventariobyl.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3dm-RKdY82FC7_PGpVXPhrT40XO4Zo3k',
    appId: '1:422878767311:android:f2d8545fc1c4420ff1efba',
    messagingSenderId: '422878767311',
    projectId: 'inventariobyl',
    storageBucket: 'inventariobyl.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBemNSYbXoFe2FOMnbiRWsQx7FmhS6kgwk',
    appId: '1:422878767311:ios:b7b48269185a393df1efba',
    messagingSenderId: '422878767311',
    projectId: 'inventariobyl',
    storageBucket: 'inventariobyl.firebasestorage.app',
    iosBundleId: 'com.example.inventarioMuebleriaByl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBemNSYbXoFe2FOMnbiRWsQx7FmhS6kgwk',
    appId: '1:422878767311:ios:b7b48269185a393df1efba',
    messagingSenderId: '422878767311',
    projectId: 'inventariobyl',
    storageBucket: 'inventariobyl.firebasestorage.app',
    iosBundleId: 'com.example.inventarioMuebleriaByl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs-MTPzF0uGsWGLEGZXz_7d913rUjrOZc',
    appId: '1:422878767311:web:789ca037fc8488a5f1efba',
    messagingSenderId: '422878767311',
    projectId: 'inventariobyl',
    authDomain: 'inventariobyl.firebaseapp.com',
    storageBucket: 'inventariobyl.firebasestorage.app',
  );
}
